name: CurseForge Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Package and upload
        uses: BigWigsMods/packager@v2
        with:
          args: -p 1324134
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
